name: "String verifier"
description: "Verify that strings follow the regex pattern and match groups"
author: "Ralfs Zangis"
inputs:
  expression:
    description: "Regex string for string verification"
    required: true
  strings:
    description: "List of strings to verify"
    required: true
outputs:
  groups:
    description: "The matching groups (based on regex)"
runs:
  using: "docker"
  image: "Dockerfile"